--
-- PostgreSQL database dump
--

\restrict qCdmFOG7ktw3TSoQAVst72tJgRL7USxFnklcKk01mGokav6fRjfKSf5hgJh6hjg

-- Dumped from database version 18.3 (Debian 18.3-1.pgdg12+1)
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: booking_appointment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.booking_appointment (
    id bigint NOT NULL,
    full_name character varying(200) NOT NULL,
    who character varying(20) NOT NULL,
    grade character varying(10) NOT NULL,
    phone character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    message text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    slot_id bigint NOT NULL,
    address character varying(300) NOT NULL,
    child_birthdate date,
    child_name character varying(200) NOT NULL,
    kindergarten character varying(200) NOT NULL,
    parent_name character varying(200) NOT NULL,
    appointment_type_id bigint,
    parent_phone character varying(20) NOT NULL
);


--
-- Name: booking_appointment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.booking_appointment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_appointment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: booking_appointmenttype; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.booking_appointmenttype (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    form_type character varying(20) NOT NULL,
    description text NOT NULL
);


--
-- Name: booking_appointmenttype_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.booking_appointmenttype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_appointmenttype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: booking_appointmenttype_psychologists; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.booking_appointmenttype_psychologists (
    id bigint NOT NULL,
    appointmenttype_id bigint CONSTRAINT booking_appointmenttype_psychologis_appointmenttype_id_not_null NOT NULL,
    psychologist_id bigint NOT NULL
);


--
-- Name: booking_appointmenttype_psychologists_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.booking_appointmenttype_psychologists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_appointmenttype_psychologists_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: booking_psychologist; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.booking_psychologist (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    grades character varying(100) NOT NULL,
    cabinet character varying(50) NOT NULL,
    phone character varying(20) NOT NULL,
    photo character varying(100) NOT NULL,
    email character varying(254) NOT NULL
);


--
-- Name: booking_psychologist_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.booking_psychologist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_psychologist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: booking_timeslot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.booking_timeslot (
    id bigint NOT NULL,
    date date NOT NULL,
    "time" time without time zone NOT NULL,
    is_available boolean NOT NULL,
    psychologist_id bigint NOT NULL
);


--
-- Name: booking_timeslot_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.booking_timeslot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.booking_timeslot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add Временной слот	7	add_timeslot
26	Can change Временной слот	7	change_timeslot
27	Can delete Временной слот	7	delete_timeslot
28	Can view Временной слот	7	view_timeslot
29	Can add Запись	8	add_appointment
30	Can change Запись	8	change_appointment
31	Can delete Запись	8	delete_appointment
32	Can view Запись	8	view_appointment
33	Can add Тип приёма	9	add_appointmenttype
34	Can change Тип приёма	9	change_appointmenttype
35	Can delete Тип приёма	9	delete_appointmenttype
36	Can view Тип приёма	9	view_appointmenttype
37	Can add Психолог	10	add_psychologist
38	Can change Психолог	10	change_psychologist
39	Can delete Психолог	10	delete_psychologist
40	Can view Психолог	10	view_psychologist
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$cPfMqg2J4L0siqzk2T7iwE$Nzico6W2emRCj66+Bdy/F4/U66RPs/eFNhk2FBblZ+E=	2026-06-08 00:11:21.922686+00	t	admin			admin@lyceum23.ru	t	t	2026-04-11 07:48:13.343531+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: booking_appointment; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.booking_appointment (id, full_name, who, grade, phone, email, message, created_at, slot_id, address, child_birthdate, child_name, kindergarten, parent_name, appointment_type_id, parent_phone) FROM stdin;
13							2026-04-17 14:19:16.240791+00	159	г. Калининград ул. Гайдара 103,7	2019-09-06	Иващенко Мария Андреевна	Маленькая страна	Иващенко Ольга Александровна	2	89097767235
14							2026-04-17 14:24:25.317068+00	153	Большое Исаково, ул. Мира, д. 47	2019-02-28	Надцонов Михаил Денисович	Геолог	Надцонов Денис Викторович	2	+79050725115
15							2026-04-17 15:04:35.685082+00	162	г. Калининград, ул. Житомирская, д. 10, кв. 9	2019-12-04	Бугрова Арина Георгиевна	Академия Детства	Гущина Анна Олеговна	2	+79097750199
21							2026-04-17 21:58:54.064967+00	155	Калининград, Стрелецкая 21а, 54	2020-02-07	Аксенова Майя Сергеевна	-	Аксенова Екатерина Евгеньевна	2	+79058261185
22							2026-04-18 07:11:51.001915+00	160	г. Калининград, Московский проспект, д. 30, кв. 26	2019-08-04	Краснослободцева Вера Евгеньевна	Детский сад № 15	Краснослободцева Юлия Марсовна	2	+79218533308
23							2026-04-18 08:03:40.646153+00	163	г.Калининград, Бородинская 1Б	2019-02-05	Чернявская Виктория Андреевна	14	Чернявская Мария Владимировна	2	89257977501
24							2026-04-18 11:52:13.259131+00	154	Калининград, ул. Сержанта-Колоскова 6а 2 кв21	2019-07-04	Рязанцева Елизавета	1	Рязанцева Юлия Сергеевна	2	+79003459710
25							2026-04-18 11:56:58.327305+00	156	Калининград улица Евгения Колесникова 8/3	2019-11-15	Офицерова Анна Александровна	Детский сад 2	Офицерова Кристина Васильевна	2	89506783290
26							2026-04-19 18:28:17.438296+00	161	Калининград, Галицкого 24-24	2018-12-26	Ротко Егор Евгеньевич	1	Ротко Валентина Павловна	2	+79992554563
27							2026-04-19 21:34:17.220092+00	157	г Калининград Сибирская д27 кв 19	2020-02-28	Шимпф Аливия Антоновна	0	Шимпф Наталия Евгеньевна	2	+79118641364
28							2026-04-20 05:34:39.648863+00	165	Г. Калининград, ул. Краснооктябрьская, д. 13. Кв. 32	2019-05-24	Самогородский Денис Владимирович	107	Самогородский Наталия Сергеевна	2	+79632944550
29							2026-04-20 08:58:50.779706+00	164	г. Калининград , ул. Ю. Гагарина 2а-3-43	2019-11-27	Ягненкова Вероника Евгеньевна	Детский сад 94	Ягненкова Юлия Владимировна	2	+79216165859
30							2026-04-20 15:14:36.429527+00	158	п. Голубево, 2-я Парковая, 7	2019-01-17	Базылевский Александр Алексеевич	135	Базылевская Наталья Олеговна	2	+79062375306
31							2026-04-24 05:46:16.04204+00	166	Калининград ул генерала Галицкого	2018-12-02	Карпушин Артём Кириллович	107	Карпушина Светлана Сергеевна	2	+79062361437
32							2026-04-24 06:11:21.425056+00	170	ул. Мариупольская	2020-01-16	Аникина Василиса Вадимовна	101	Аникина Ирина Сергеевна	2	+79992550124
33							2026-04-24 06:12:09.652617+00	173	Калининград ул. Генерала Галицкого 24	2019-03-12	Апполонов Иван Дмитриевич	1	Апполонова Екатерина Александровна	2	89114830360
34							2026-04-24 06:32:49.711126+00	172	Калининград, Московский проспект, д.15, кв 30	2019-09-10	Марчук Полина Максимовна	1	Марчук Руфина Дмитриевна	2	+79118530793
35							2026-04-24 07:07:51.639321+00	167	г. Калининград, ул. Житомирская, д.18, кв. 9	2019-07-03	Минаков Кирилл Романович	87	Минаков Роман Сергеевич	2	+79210056088
36							2026-04-24 07:24:53.700325+00	168	Г Калининград, Галицкого 31 кв 7	2019-07-24	Кащук Елизавета Алексеевна	14	Кащук Анастасия Андреевна	2	89114761976
37							2026-04-24 08:58:57.264072+00	169	г. Калининград, ул. Краснооктябрьская д. 13 кв. 24	2019-08-17	Кошлева Мария Максимовна	Академия детства	Зубицкая Ольга Игоревна	2	+79062122510
38							2026-04-24 11:19:43.642675+00	171	г.Калининград ул.Суворова д.42 кв.129	2019-05-18	Шкварова Мария Александровна	№ 28	Шкварова Екатерина Константиновна	2	+79062330492
39							2026-05-04 08:56:06.517191+00	174	г. Калининград,  ул. Крылова,  д. 30Б	2019-03-05	Ростовский Лев Иванович	59	Ростовская Ольга Владимировна	2	+79218502350
40							2026-05-04 09:41:26.278376+00	180	г. Калининград	2019-09-21	Колесник Матвей Николаевич	-	Колесник Ольга Алексеевна	2	+79814555255
41							2026-05-04 14:31:02.227155+00	176	Калининград, Генерала Галицкого 24,75	2019-09-01	Гузыченко Александр Михайлович	1	Терещенко Ульяна Владимировна	2	79521134676
42							2026-05-04 14:43:27.687275+00	177	Калининград, Генерала Галицкого 24,75	2019-09-01	Гузыченко Александр Михайлович	1	Терещенко Ульяна Владимировна	2	79521134676
43							2026-05-04 18:50:20.558053+00	178	г. Калининград, ул. Богатырская 3А	2019-02-25	Буслова Агата-Александра Александровна	55	Буслова Марина Алексеевна	2	+79097981158
44							2026-05-05 09:59:57.276115+00	181	Калининград, Каштановая аллея, 42-1	2019-03-27	Штукарь Мирон Анатольевич	"Успешный малыш"	Алина Игоревна	2	+79114504368
45							2026-05-05 10:03:13.574441+00	182	Калининград, ул. Генерала Галицкого, 31-7	2019-07-14	Рябинина Стефания Юрьевна	"Успешный малыш"	Бэлла Владимировна	2	+7911-488-18-88
46							2026-05-05 10:06:56.818819+00	183	Г. Калининград, Московский пр, 13-9	2019-07-05	Николаева Екатерина Алексеевна	107	Смирнова Наталья Александровна	2	89814541017
47							2026-05-05 16:31:50.102063+00	179	Калининград ул. Маршала Баграмяна, д. 18,кв.30	2019-06-21	Глазунов Виталий Дмитриевич	Не посещал	Глазунова Наталья Павловна	2	+79117761576
48							2026-05-08 10:20:59.354804+00	184	Г. Калининград , московский проспект	2019-09-08	Бобров Сергей Игоревич	1	Боброва Ани Артуровна	2	+79097752339
49							2026-05-08 10:23:05.867668+00	185	Г. Калининград, московский проспект	2019-09-08	Бобров Сергей Игоревич	1	Боброва Ани Артуровна	2	+79097752339
50							2026-05-08 12:44:58.963446+00	186	Г. Калининград, Московский пр, 13-9	2019-07-24	Николаева Екатерина Алексеевна	107	Смирнова Наталья Александровна	2	+79814541017
51							2026-05-08 12:50:57.422903+00	187	Г. Калининград, Московский пр. , 13-9	2019-07-24	Николаева Екатерина Алексеевна	107	Смирнова Наталья Александровна	2	+79814541017
52							2026-05-18 05:39:33.042205+00	191	Гурьевский р-н, пос. Родники, ул. Зеленая, д. 4	2019-07-09	Анпилогов Леонид Иванович	133	Анпилогова Ирина Олеговна	2	+79052451460
53							2026-05-18 05:40:28.383526+00	189	г. Калининград ул. Вагнера 4-12	2018-11-14	Отставных Каролина Александровна	87	Отставных Ольга Михайловна	2	+79114794244
58							2026-05-18 06:27:44.117513+00	193	г. Калининград	2018-10-08	Орлов Олег Игоревич	нет	Орлов Игорь Викторович	2	+7 (936) 666-65-65
75							2026-05-18 10:43:16.529068+00	194	Г. Калининград, московский проспект 11,12	2019-04-05	Левченко Павел александрвоич	22	Левченко Александр Викторович	2	+79212685242
91							2026-05-18 11:05:50.549436+00	192	Московский пр-кт 11,12	2019-04-05	Левченко Павел Александрович	22	Ковалева Светлана Викторовна	2	89210073969
94							2026-05-18 11:23:23.348051+00	188	Калининград,  ул Галицкого 24-40	2019-02-03	Филина София Дмитриевна	22 гимназия	Филина Наталья Александровна	2	+79521144245
95							2026-05-18 12:02:13.676739+00	190	г калининград ул Больничная д 6-8 кв 35	2019-05-13	Попов Демид Денисович	"Будь первым"	Попова Людмила Юрьевна	2	+79114556130
96							2026-05-18 13:06:42.126458+00	195	г Калининград, ул Корабельная 3 кв 53	2019-10-17	Нуркова София	Детский сад 135	Нуркова Ольга Александровна	2	+79210083490
100							2026-05-23 09:23:05.75654+00	202	Г. Калининград, ул Вагнера 5 - 2	2019-08-05	Кононович Максим Александрович	2	Марк Валерия Андреевна	2	+79118573280
102							2026-05-23 10:13:15.157462+00	199	г. Калининград ул. Загорская д. 3 кв. 5	2018-12-06	Мамедов Тагир Станиславович	128	Мамедова Ирина Викторовна	2	+79520528885
103							2026-05-25 08:17:57.354326+00	201	г. Калининград ул. Звездная 21 кв 5	2019-08-30	Абубокарова Аделина Тагировна	87	Цыганова Марина Геннадьевна	2	+79520515991
104							2026-05-25 09:08:55.502608+00	203	Московский Проспект 21, 27	2019-07-18	Милованов Данила Александрович	87	Милованова Анастасия Игоревна	2	+79097888707
105							2026-05-25 21:19:55.615054+00	204	г. Калининград , Московская проспект 9-4	2019-10-29	Лобанова Алина Антонова	87	Лобанова Елена Валерьевна	2	+79062197792
106							2026-05-29 09:04:12.485601+00	210	Калининград, будкова 20-109	2019-06-24	Козлов Лука Игоревич	БУДЬ 1	Спирко Галина Юрьевна	2	89114777779
107							2026-05-29 09:09:05.113927+00	208	г. Калининград Ленинский проспект 8 кв 11	2019-07-04	Федоров Владислав Антонович	101	Волкова Ольга Игоревна	2	+79632921345
108							2026-05-29 09:19:48.080673+00	209	г. Калининград, СНТ "Колосок", ул. Садовая, д. 3	2019-03-06	Захаров Роберт Антонович	Гимназия N 22	Захарова Мария Владимировна	2	+7(911) 861-83-56
109							2026-05-29 10:05:42.991269+00	211	Калининград, Ул. Двинская, д.24	2019-06-29	Бочаров Даниил Игоревич	Нет	Бочарова Анастасия Юрьевна	2	89114642336
110							2026-05-29 11:24:33.957748+00	212	г.Калининград,ул.Звёздная 7-9	2018-12-27	Курова Каролина Кирилловна	111	Курова Дана Сергеевна	2	+79506738170
111							2026-05-29 11:33:56.143428+00	213	Калининград, Московский проспект 11-4	2019-08-09	Родионов Артём Тимурович	87	Родионова Дарья Георгиевна	2	89114900800
112							2026-05-29 21:48:40.105987+00	214	Г. Калининград, ул. Марата, д7 кв 27	2019-01-09	Кириков Егор Денисович	МАДОУ Детский сад №1	Кирикова Виктория Игоревна	2	+79216125696
113							2026-06-01 06:52:47.921767+00	217	Г.Калинград ул.Галицкого 23.9	2019-07-30	Довидайтите Забава Владимировна	Золотой ключик	Довидайтите Рита Антановна	2	89097986786
114							2026-06-04 09:57:49.156667+00	216	Г.Калинград ул.Галицкого 23.9	2019-06-30	Довидайтите Забава Владимировна	Золотой ключик	Довидайтите Рита Антановна	2	89097986786
115							2026-06-05 06:41:46.688287+00	215		\N				\N	
\.


--
-- Data for Name: booking_appointmenttype; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.booking_appointmenttype (id, name, form_type, description) FROM stdin;
2	Психологическое собеседование дошкольников	preschool_exam	Психологическое собеседование для дошкольников перед поступлением в лицей. Диагностика готовности к школе, развитие познавательных процессов, адаптационный потенциал. Длительность: 45-60 минут.
\.


--
-- Data for Name: booking_appointmenttype_psychologists; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.booking_appointmenttype_psychologists (id, appointmenttype_id, psychologist_id) FROM stdin;
3	2	1
\.


--
-- Data for Name: booking_psychologist; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.booking_psychologist (id, name, grades, cabinet, phone, photo, email) FROM stdin;
2	Ворожейкина Ирина Вячеславовна	7-11 классы	312	+7 (4012) 46-69-11	images/psychologist/vorozheikina.jpg	
1	Ганиева Маргарита Викторовна	1-6 классы, дошкольники	психолога - I этаж	+7 (4012) 46-69-11	images/psychologist/ganieva.jpg	
\.


--
-- Data for Name: booking_timeslot; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.booking_timeslot (id, date, "time", is_available, psychologist_id) FROM stdin;
159	2026-04-22	10:00:00	f	1
153	2026-04-21	08:15:00	f	1
162	2026-04-25	11:00:00	f	1
155	2026-04-21	09:30:00	f	1
160	2026-04-25	10:00:00	f	1
163	2026-04-25	11:30:00	f	1
154	2026-04-21	09:00:00	f	1
156	2026-04-22	08:15:00	f	1
161	2026-04-25	10:30:00	f	1
157	2026-04-22	09:00:00	f	1
165	2026-04-25	13:00:00	f	1
164	2026-04-25	12:30:00	f	1
158	2026-04-22	09:30:00	f	1
166	2026-04-28	08:15:00	f	1
170	2026-04-30	08:15:00	f	1
173	2026-04-30	10:00:00	f	1
172	2026-04-30	09:30:00	f	1
167	2026-04-28	09:00:00	f	1
168	2026-04-28	09:30:00	f	1
169	2026-04-28	10:00:00	f	1
171	2026-04-30	09:00:00	f	1
175	2026-05-05	09:00:00	t	1
174	2026-05-05	08:15:00	f	1
180	2026-05-07	10:00:00	f	1
176	2026-05-05	09:30:00	f	1
177	2026-05-05	10:00:00	f	1
178	2026-05-07	08:15:00	f	1
181	2026-05-08	14:00:00	f	1
182	2026-05-08	14:30:00	f	1
183	2026-05-08	15:00:00	f	1
179	2026-05-07	09:00:00	f	1
184	2026-05-14	15:00:00	f	1
185	2026-05-14	15:30:00	f	1
186	2026-05-14	16:00:00	f	1
187	2026-05-14	16:30:00	f	1
191	2026-05-19	10:00:00	f	1
189	2026-05-19	09:00:00	f	1
211	2026-06-08	14:30:00	f	1
212	2026-06-10	08:30:00	f	1
213	2026-06-10	09:00:00	f	1
214	2026-06-10	09:30:00	f	1
193	2026-05-21	15:00:00	f	1
217	2026-06-11	09:30:00	f	1
216	2026-06-11	09:00:00	f	1
215	2026-06-11	08:30:00	f	1
194	2026-05-21	15:30:00	f	1
192	2026-05-21	14:30:00	f	1
188	2026-05-19	08:15:00	f	1
190	2026-05-19	09:30:00	f	1
195	2026-05-21	16:00:00	f	1
200	2026-05-25	11:00:00	t	1
202	2026-05-26	10:30:00	f	1
199	2026-05-25	10:30:00	f	1
198	2026-05-25	10:00:00	t	1
201	2026-05-26	10:00:00	f	1
203	2026-05-26	11:00:00	f	1
204	2026-05-29	10:00:00	f	1
205	2026-05-29	10:30:00	f	1
206	2026-05-29	11:00:00	f	1
207	2026-05-29	11:30:00	f	1
210	2026-06-08	14:00:00	f	1
208	2026-06-08	13:00:00	f	1
209	2026-06-08	13:30:00	f	1
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-04-11 08:18:26.469947+00	1	Ганиева Маргарита Викторовна (1-4 классы, дошкольники)	1	[{"added": {}}]	10	1
2	2026-04-11 08:20:06.383192+00	1	Консультация психолога	1	[{"added": {}}]	9	1
3	2026-04-11 08:20:32.729095+00	2	Психологическое собеседование дошкольников	1	[{"added": {}}]	9	1
4	2026-04-11 08:56:03.040092+00	2	Дорошенко Татьяна Васильевна (5-11 классы)	1	[{"added": {}}]	10	1
5	2026-04-11 13:01:48.934696+00	2	Психологическое собеседование дошкольников	2	[]	9	1
6	2026-04-11 13:02:00.730743+00	1	Консультация психолога	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u043d\\u043e \\u0443 \\u043f\\u0441\\u0438\\u0445\\u043e\\u043b\\u043e\\u0433\\u043e\\u0432"]}}]	9	1
7	2026-04-11 13:02:07.738391+00	2	Психологическое собеседование дошкольников	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u043d\\u043e \\u0443 \\u043f\\u0441\\u0438\\u0445\\u043e\\u043b\\u043e\\u0433\\u043e\\u0432"]}}]	9	1
8	2026-04-11 13:29:35.085808+00	2	Дорошенко Татьяна Васильевна (5-11 классы)	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0431\\u0438\\u043d\\u0435\\u0442", "\\u0422\\u0435\\u043b\\u0435\\u0444\\u043e\\u043d", "\\u0424\\u043e\\u0442\\u043e"]}}]	10	1
9	2026-04-11 13:30:02.719198+00	1	Ганиева Маргарита Викторовна (1-4 классы, дошкольники)	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0431\\u0438\\u043d\\u0435\\u0442", "\\u0422\\u0435\\u043b\\u0435\\u0444\\u043e\\u043d", "\\u0424\\u043e\\u0442\\u043e"]}}]	10	1
10	2026-04-11 13:30:12.10861+00	2	Дорошенко Татьяна Васильевна (5-11 классы)	2	[{"changed": {"fields": ["\\u0424\\u043e\\u0442\\u043e"]}}]	10	1
11	2026-04-11 13:30:47.209339+00	2	Дорошенко Татьяна Васильевна (5-11 классы)	2	[{"changed": {"fields": ["\\u0422\\u0435\\u043b\\u0435\\u0444\\u043e\\u043d"]}}]	10	1
12	2026-04-11 13:30:52.937721+00	1	Ганиева Маргарита Викторовна (1-4 классы, дошкольники)	2	[{"changed": {"fields": ["\\u0422\\u0435\\u043b\\u0435\\u0444\\u043e\\u043d"]}}]	10	1
13	2026-04-12 11:45:20.060663+00	2	Ворожейкина Ирина Вячеславовна (5-11 классы)	2	[{"changed": {"fields": ["\\u0424\\u0418\\u041e"]}}]	10	1
14	2026-04-12 12:00:02.842935+00	1	Ганиева Маргарита Викторовна (1-4 классы, дошкольники)	2	[{"changed": {"fields": ["\\u0422\\u0435\\u043b\\u0435\\u0444\\u043e\\u043d"]}}]	10	1
15	2026-04-12 12:06:08.031564+00	2	Ворожейкина Ирина Вячеславовна (5-11 классы)	2	[{"changed": {"fields": ["\\u041f\\u0443\\u0442\\u044c \\u043a \\u0444\\u043e\\u0442\\u043e \\u0432 \\u0444\\u0430\\u0439\\u043b\\u0430\\u0445 \\u0441\\u0430\\u0439\\u0442\\u0430"]}}]	10	1
16	2026-04-12 12:06:31.839753+00	2	Ворожейкина Ирина Вячеславовна (5-11 классы)	2	[{"changed": {"fields": ["\\u041f\\u0443\\u0442\\u044c \\u043a \\u0444\\u043e\\u0442\\u043e \\u0432 \\u0444\\u0430\\u0439\\u043b\\u0430\\u0445 \\u0441\\u0430\\u0439\\u0442\\u0430"]}}]	10	1
17	2026-04-12 12:06:36.390811+00	1	Ганиева Маргарита Викторовна (1-4 классы, дошкольники)	2	[{"changed": {"fields": ["\\u041f\\u0443\\u0442\\u044c \\u043a \\u0444\\u043e\\u0442\\u043e \\u0432 \\u0444\\u0430\\u0439\\u043b\\u0430\\u0445 \\u0441\\u0430\\u0439\\u0442\\u0430"]}}]	10	1
18	2026-04-12 12:25:05.351488+00	4	stepan voytov → Ворожейкина Ирина Вячеславовна (5-11 классы) | Консультация психолога	3		8	1
19	2026-04-12 12:25:05.354483+00	2	Иванов Иван Иванович → Ворожейкина Ирина Вячеславовна (5-11 классы) | Психологическое собеседование дошкольников	3		8	1
20	2026-04-12 12:25:05.356745+00	3	3424234242 → Ворожейкина Ирина Вячеславовна (5-11 классы) | Психологическое собеседование дошкольников	3		8	1
21	2026-04-12 12:25:05.359695+00	1	fjkldhjdfhjksdf → Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
22	2026-04-12 12:25:05.361802+00	5	dfaasdfa → Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | Консультация психолога	3		8	1
23	2026-04-12 12:25:05.365427+00	6	fjkldhjdfhjksdf → Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
24	2026-04-12 12:25:05.367545+00	7	Иванов Иван Иванович → Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
25	2026-04-12 12:25:05.369626+00	8	Иванов Иван Иванович → Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
26	2026-04-12 12:25:42.45574+00	61	Ворожейкина Ирина Вячеславовна (5-11 классы) | 13.04.2026 10:00 ✗	3		7	1
27	2026-04-12 12:25:42.463305+00	62	Ворожейкина Ирина Вячеславовна (5-11 классы) | 13.04.2026 10:30 ✗	3		7	1
28	2026-04-12 12:25:42.465462+00	63	Ворожейкина Ирина Вячеславовна (5-11 классы) | 13.04.2026 11:00 ✗	3		7	1
29	2026-04-12 12:25:42.467969+00	64	Ворожейкина Ирина Вячеславовна (5-11 классы) | 13.04.2026 11:30 ✓	3		7	1
30	2026-04-12 12:25:42.471265+00	65	Ворожейкина Ирина Вячеславовна (5-11 классы) | 13.04.2026 12:00 ✓	3		7	1
31	2026-04-12 12:25:42.475483+00	1	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 12:00 ✗	3		7	1
32	2026-04-12 12:25:42.477782+00	2	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 12:20 ✗	3		7	1
33	2026-04-12 12:25:42.479822+00	66	Ворожейкина Ирина Вячеславовна (5-11 классы) | 13.04.2026 12:30 ✓	3		7	1
34	2026-04-12 12:25:42.515673+00	3	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 12:40 ✗	3		7	1
35	2026-04-12 12:25:42.521043+00	67	Ворожейкина Ирина Вячеславовна (5-11 классы) | 13.04.2026 13:00 ✓	3		7	1
36	2026-04-12 12:25:42.52433+00	4	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 13:00 ✗	3		7	1
37	2026-04-12 12:25:42.528295+00	5	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 13:20 ✓	3		7	1
38	2026-04-12 12:25:42.531915+00	68	Ворожейкина Ирина Вячеславовна (5-11 классы) | 13.04.2026 13:30 ✓	3		7	1
39	2026-04-12 12:25:42.534004+00	6	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 13:40 ✓	3		7	1
40	2026-04-12 12:25:42.538759+00	7	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 14:00 ✓	3		7	1
41	2026-04-12 12:25:42.542489+00	8	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 14:20 ✓	3		7	1
42	2026-04-12 12:25:42.54448+00	9	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 14:40 ✓	3		7	1
43	2026-04-12 12:25:42.548366+00	10	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 15:00 ✓	3		7	1
44	2026-04-12 12:25:42.550367+00	11	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 15:20 ✓	3		7	1
45	2026-04-12 12:25:42.553253+00	12	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 15:40 ✓	3		7	1
46	2026-04-12 12:25:42.557225+00	69	Ворожейкина Ирина Вячеславовна (5-11 классы) | 14.04.2026 10:00 ✓	3		7	1
47	2026-04-12 12:25:42.559211+00	70	Ворожейкина Ирина Вячеславовна (5-11 классы) | 14.04.2026 10:30 ✓	3		7	1
48	2026-04-12 12:25:42.561124+00	71	Ворожейкина Ирина Вячеславовна (5-11 классы) | 14.04.2026 11:00 ✓	3		7	1
49	2026-04-12 12:25:42.565269+00	72	Ворожейкина Ирина Вячеславовна (5-11 классы) | 14.04.2026 11:30 ✓	3		7	1
50	2026-04-12 12:25:42.567212+00	73	Ворожейкина Ирина Вячеславовна (5-11 классы) | 14.04.2026 12:00 ✓	3		7	1
51	2026-04-12 12:25:42.569124+00	13	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 12:00 ✓	3		7	1
52	2026-04-12 12:25:42.573204+00	14	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 12:20 ✓	3		7	1
53	2026-04-12 12:25:42.575045+00	74	Ворожейкина Ирина Вячеславовна (5-11 классы) | 14.04.2026 12:30 ✓	3		7	1
54	2026-04-12 12:25:42.577019+00	15	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 12:40 ✓	3		7	1
55	2026-04-12 12:25:42.578875+00	75	Ворожейкина Ирина Вячеславовна (5-11 классы) | 14.04.2026 13:00 ✓	3		7	1
56	2026-04-12 12:25:42.583216+00	16	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 13:00 ✓	3		7	1
57	2026-04-12 12:25:42.585279+00	17	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 13:20 ✓	3		7	1
58	2026-04-12 12:25:42.587156+00	76	Ворожейкина Ирина Вячеславовна (5-11 классы) | 14.04.2026 13:30 ✓	3		7	1
59	2026-04-12 12:25:42.590256+00	18	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 13:40 ✓	3		7	1
60	2026-04-12 12:25:42.592272+00	19	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 14:00 ✓	3		7	1
61	2026-04-12 12:25:42.595294+00	20	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 14:20 ✓	3		7	1
62	2026-04-12 12:25:42.597459+00	21	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 14:40 ✓	3		7	1
63	2026-04-12 12:25:42.60098+00	22	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 15:00 ✗	3		7	1
64	2026-04-12 12:25:42.603852+00	23	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 15:20 ✓	3		7	1
65	2026-04-12 12:25:42.607308+00	24	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 15:40 ✓	3		7	1
66	2026-04-12 12:25:42.610997+00	25	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 12:00 ✓	3		7	1
67	2026-04-12 12:25:42.615396+00	26	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 12:20 ✓	3		7	1
68	2026-04-12 12:25:42.620316+00	27	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 12:40 ✓	3		7	1
69	2026-04-12 12:25:42.623841+00	28	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 13:00 ✓	3		7	1
70	2026-04-12 12:25:42.627592+00	29	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 13:20 ✓	3		7	1
71	2026-04-12 12:25:42.63343+00	30	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 13:40 ✓	3		7	1
72	2026-04-12 12:25:42.635717+00	31	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 14:00 ✓	3		7	1
73	2026-04-12 12:25:42.638209+00	32	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 14:20 ✓	3		7	1
74	2026-04-12 12:25:42.648362+00	33	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 14:40 ✓	3		7	1
75	2026-04-12 12:25:42.652312+00	34	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 15:00 ✓	3		7	1
76	2026-04-12 12:25:42.657921+00	35	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 15:20 ✓	3		7	1
77	2026-04-12 12:25:42.663263+00	36	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 15:40 ✓	3		7	1
78	2026-04-12 12:25:42.667956+00	77	Ворожейкина Ирина Вячеславовна (5-11 классы) | 16.04.2026 10:00 ✓	3		7	1
79	2026-04-12 12:25:42.672246+00	78	Ворожейкина Ирина Вячеславовна (5-11 классы) | 16.04.2026 10:30 ✓	3		7	1
80	2026-04-12 12:25:42.674341+00	79	Ворожейкина Ирина Вячеславовна (5-11 классы) | 16.04.2026 11:00 ✓	3		7	1
81	2026-04-12 12:25:42.676394+00	80	Ворожейкина Ирина Вячеславовна (5-11 классы) | 16.04.2026 11:30 ✓	3		7	1
82	2026-04-12 12:25:42.680254+00	81	Ворожейкина Ирина Вячеславовна (5-11 классы) | 16.04.2026 12:00 ✓	3		7	1
83	2026-04-12 12:25:42.68232+00	37	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 12:00 ✓	3		7	1
84	2026-04-12 12:25:42.684816+00	38	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 12:20 ✓	3		7	1
85	2026-04-12 12:25:42.689297+00	82	Ворожейкина Ирина Вячеславовна (5-11 классы) | 16.04.2026 12:30 ✓	3		7	1
86	2026-04-12 12:25:42.691447+00	39	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 12:40 ✓	3		7	1
87	2026-04-12 12:25:42.693382+00	83	Ворожейкина Ирина Вячеславовна (5-11 классы) | 16.04.2026 13:00 ✓	3		7	1
88	2026-04-12 12:25:42.697263+00	40	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 13:00 ✓	3		7	1
89	2026-04-12 12:25:42.699275+00	41	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 13:20 ✓	3		7	1
90	2026-04-12 12:25:42.70319+00	84	Ворожейкина Ирина Вячеславовна (5-11 классы) | 16.04.2026 13:30 ✓	3		7	1
91	2026-04-12 12:25:42.705159+00	42	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 13:40 ✓	3		7	1
92	2026-04-12 12:25:42.708523+00	43	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 14:00 ✓	3		7	1
93	2026-04-12 12:25:42.714593+00	44	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 14:20 ✓	3		7	1
94	2026-04-12 12:25:42.716695+00	45	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 14:40 ✓	3		7	1
95	2026-04-12 12:25:42.718706+00	46	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 15:00 ✓	3		7	1
96	2026-04-12 12:25:42.724308+00	47	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 15:20 ✓	3		7	1
97	2026-04-12 12:25:42.726574+00	48	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 15:40 ✓	3		7	1
98	2026-04-12 12:25:42.728517+00	85	Ворожейкина Ирина Вячеславовна (5-11 классы) | 17.04.2026 10:00 ✓	3		7	1
99	2026-04-12 12:25:42.733797+00	86	Ворожейкина Ирина Вячеславовна (5-11 классы) | 17.04.2026 10:30 ✓	3		7	1
100	2026-04-12 12:25:42.738125+00	87	Ворожейкина Ирина Вячеславовна (5-11 классы) | 17.04.2026 11:00 ✓	3		7	1
101	2026-04-12 12:25:42.740161+00	88	Ворожейкина Ирина Вячеславовна (5-11 классы) | 17.04.2026 11:30 ✓	3		7	1
102	2026-04-12 12:25:42.742128+00	89	Ворожейкина Ирина Вячеславовна (5-11 классы) | 17.04.2026 12:00 ✓	3		7	1
103	2026-04-12 12:25:42.748526+00	49	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 12:00 ✓	3		7	1
104	2026-04-12 12:25:42.750681+00	50	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 12:20 ✓	3		7	1
105	2026-04-12 12:25:42.752756+00	90	Ворожейкина Ирина Вячеславовна (5-11 классы) | 17.04.2026 12:30 ✓	3		7	1
106	2026-04-12 12:25:42.75486+00	51	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 12:40 ✓	3		7	1
107	2026-04-12 12:25:42.756942+00	91	Ворожейкина Ирина Вячеславовна (5-11 классы) | 17.04.2026 13:00 ✓	3		7	1
108	2026-04-12 12:25:42.759028+00	52	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 13:00 ✓	3		7	1
109	2026-04-12 12:25:42.76332+00	53	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 13:20 ✓	3		7	1
110	2026-04-12 12:25:42.765493+00	92	Ворожейкина Ирина Вячеславовна (5-11 классы) | 17.04.2026 13:30 ✓	3		7	1
111	2026-04-12 12:25:42.767604+00	54	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 13:40 ✓	3		7	1
112	2026-04-12 12:25:42.775426+00	55	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 14:00 ✓	3		7	1
113	2026-04-12 12:25:42.777657+00	56	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 14:20 ✓	3		7	1
114	2026-04-12 12:25:42.77983+00	57	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 14:40 ✓	3		7	1
115	2026-04-12 12:25:42.781884+00	58	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 15:00 ✓	3		7	1
116	2026-04-12 12:25:42.786335+00	59	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 15:20 ✓	3		7	1
117	2026-04-12 12:25:42.78848+00	60	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 15:40 ✓	3		7	1
118	2026-04-16 15:12:35.215872+00	9	Войтов Стефан Витальевич → Ворожейкина Ирина Вячеславовна (5-11 классы) | Консультация психолога	3		8	1
119	2026-04-16 15:12:35.221812+00	10	папрпа → Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
120	2026-04-16 15:13:13.426087+00	133	Ворожейкина Ирина Вячеславовна (5-11 классы) | 13.04.2026 10:00 ✓	3		7	1
121	2026-04-16 15:13:13.435772+00	134	Ворожейкина Ирина Вячеславовна (5-11 классы) | 13.04.2026 11:00 ✓	3		7	1
122	2026-04-16 15:13:13.439311+00	135	Ворожейкина Ирина Вячеславовна (5-11 классы) | 13.04.2026 12:00 ✓	3		7	1
123	2026-04-16 15:13:13.443518+00	93	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 12:00 ✓	3		7	1
124	2026-04-16 15:13:13.449364+00	94	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 12:30 ✓	3		7	1
125	2026-04-16 15:13:13.454714+00	136	Ворожейкина Ирина Вячеславовна (5-11 классы) | 13.04.2026 13:00 ✓	3		7	1
126	2026-04-16 15:13:13.462025+00	95	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 13:00 ✓	3		7	1
127	2026-04-16 15:13:13.46439+00	96	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 13:30 ✓	3		7	1
128	2026-04-16 15:13:13.469366+00	97	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 14:00 ✓	3		7	1
129	2026-04-16 15:13:13.476659+00	98	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 14:30 ✓	3		7	1
130	2026-04-16 15:13:13.516361+00	99	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 15:00 ✓	3		7	1
131	2026-04-16 15:13:13.520318+00	100	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 13.04.2026 15:30 ✓	3		7	1
132	2026-04-16 15:13:13.522787+00	137	Ворожейкина Ирина Вячеславовна (5-11 классы) | 14.04.2026 10:00 ✓	3		7	1
133	2026-04-16 15:13:13.525043+00	138	Ворожейкина Ирина Вячеславовна (5-11 классы) | 14.04.2026 11:00 ✗	3		7	1
134	2026-04-16 15:13:13.527385+00	139	Ворожейкина Ирина Вячеславовна (5-11 классы) | 14.04.2026 12:00 ✓	3		7	1
135	2026-04-16 15:13:13.53038+00	101	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 12:00 ✓	3		7	1
136	2026-04-16 15:13:13.532773+00	102	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 12:30 ✓	3		7	1
137	2026-04-16 15:13:13.53511+00	140	Ворожейкина Ирина Вячеславовна (5-11 классы) | 14.04.2026 13:00 ✓	3		7	1
138	2026-04-16 15:13:13.537359+00	103	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 13:00 ✓	3		7	1
139	2026-04-16 15:13:13.539985+00	104	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 13:30 ✓	3		7	1
140	2026-04-16 15:13:13.542256+00	105	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 14:00 ✓	3		7	1
141	2026-04-16 15:13:13.544995+00	106	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 14:30 ✓	3		7	1
142	2026-04-16 15:13:13.547823+00	107	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 15:00 ✓	3		7	1
143	2026-04-16 15:13:13.55024+00	108	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 14.04.2026 15:30 ✓	3		7	1
144	2026-04-16 15:13:13.553483+00	141	Ворожейкина Ирина Вячеславовна (5-11 классы) | 15.04.2026 10:00 ✓	3		7	1
145	2026-04-16 15:13:13.556971+00	142	Ворожейкина Ирина Вячеславовна (5-11 классы) | 15.04.2026 11:00 ✓	3		7	1
146	2026-04-16 15:13:13.559258+00	143	Ворожейкина Ирина Вячеславовна (5-11 классы) | 15.04.2026 12:00 ✓	3		7	1
147	2026-04-16 15:13:13.561405+00	109	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 12:00 ✓	3		7	1
148	2026-04-16 15:13:13.563421+00	110	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 12:30 ✓	3		7	1
149	2026-04-16 15:13:13.56545+00	144	Ворожейкина Ирина Вячеславовна (5-11 классы) | 15.04.2026 13:00 ✓	3		7	1
150	2026-04-16 15:13:13.567558+00	111	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 13:00 ✓	3		7	1
151	2026-04-16 15:13:13.570275+00	112	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 13:30 ✓	3		7	1
152	2026-04-16 15:13:13.572302+00	113	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 14:00 ✓	3		7	1
153	2026-04-16 15:13:13.574724+00	114	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 14:30 ✓	3		7	1
154	2026-04-16 15:13:13.578242+00	115	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 15:00 ✓	3		7	1
155	2026-04-16 15:13:13.581124+00	116	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 15.04.2026 15:30 ✓	3		7	1
156	2026-04-16 15:13:13.584218+00	145	Ворожейкина Ирина Вячеславовна (5-11 классы) | 16.04.2026 10:00 ✓	3		7	1
157	2026-04-16 15:13:13.590888+00	146	Ворожейкина Ирина Вячеславовна (5-11 классы) | 16.04.2026 11:00 ✓	3		7	1
158	2026-04-16 15:13:13.593234+00	147	Ворожейкина Ирина Вячеславовна (5-11 классы) | 16.04.2026 12:00 ✓	3		7	1
159	2026-04-16 15:13:13.595499+00	117	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 12:00 ✓	3		7	1
160	2026-04-16 15:13:13.616409+00	118	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 12:30 ✗	3		7	1
161	2026-04-16 15:13:13.62103+00	148	Ворожейкина Ирина Вячеславовна (5-11 классы) | 16.04.2026 13:00 ✓	3		7	1
162	2026-04-16 15:13:13.623582+00	119	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 13:00 ✓	3		7	1
163	2026-04-16 15:13:13.626007+00	120	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 13:30 ✓	3		7	1
164	2026-04-16 15:13:13.628259+00	121	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 14:00 ✓	3		7	1
165	2026-04-16 15:13:13.630386+00	122	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 14:30 ✓	3		7	1
166	2026-04-16 15:13:13.632747+00	123	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 15:00 ✓	3		7	1
167	2026-04-16 15:13:13.634872+00	124	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 16.04.2026 15:30 ✓	3		7	1
168	2026-04-16 15:13:13.63783+00	149	Ворожейкина Ирина Вячеславовна (5-11 классы) | 17.04.2026 10:00 ✓	3		7	1
169	2026-04-16 15:13:13.640473+00	150	Ворожейкина Ирина Вячеславовна (5-11 классы) | 17.04.2026 11:00 ✓	3		7	1
170	2026-04-16 15:13:13.643564+00	151	Ворожейкина Ирина Вячеславовна (5-11 классы) | 17.04.2026 12:00 ✓	3		7	1
171	2026-04-16 15:13:13.64573+00	125	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 12:00 ✓	3		7	1
172	2026-04-16 15:13:13.648347+00	126	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 12:30 ✓	3		7	1
173	2026-04-16 15:13:13.650545+00	152	Ворожейкина Ирина Вячеславовна (5-11 классы) | 17.04.2026 13:00 ✓	3		7	1
174	2026-04-16 15:13:13.653838+00	127	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 13:00 ✓	3		7	1
175	2026-04-16 15:13:13.656179+00	128	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 13:30 ✓	3		7	1
176	2026-04-16 15:13:13.65889+00	129	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 14:00 ✓	3		7	1
177	2026-04-16 15:13:13.661386+00	130	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 14:30 ✓	3		7	1
178	2026-04-16 15:13:13.664601+00	131	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 15:00 ✓	3		7	1
179	2026-04-16 15:13:13.667481+00	132	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 17.04.2026 15:30 ✓	3		7	1
180	2026-04-16 15:13:53.600595+00	153	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 21.04.2026 08:15 ✓	1	[{"added": {}}]	7	1
181	2026-04-16 15:14:29.549928+00	154	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 21.04.2026 09:00 ✓	1	[{"added": {}}]	7	1
182	2026-04-16 15:14:52.199503+00	155	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 21.04.2026 09:30 ✓	1	[{"added": {}}]	7	1
183	2026-04-16 15:14:55.801144+00	155	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 21.04.2026 09:30 ✓	2	[]	7	1
184	2026-04-16 15:15:21.999686+00	156	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 22.04.2026 08:15 ✓	1	[{"added": {}}]	7	1
185	2026-04-16 15:15:31.697399+00	157	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 22.04.2026 09:00 ✓	1	[{"added": {}}]	7	1
186	2026-04-16 15:15:43.797788+00	158	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 22.04.2026 09:30 ✓	1	[{"added": {}}]	7	1
187	2026-04-16 15:15:57.900076+00	159	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 22.04.2026 10:00 ✓	1	[{"added": {}}]	7	1
188	2026-04-16 15:16:16.395831+00	160	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 25.04.2026 10:00 ✓	1	[{"added": {}}]	7	1
189	2026-04-16 15:16:39.302959+00	161	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 25.04.2026 10:30 ✓	1	[{"added": {}}]	7	1
190	2026-04-16 15:16:52.197255+00	162	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 25.04.2026 11:00 ✓	1	[{"added": {}}]	7	1
191	2026-04-16 15:17:15.135892+00	163	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 25.04.2026 11:30 ✓	1	[{"added": {}}]	7	1
192	2026-04-16 15:17:27.831601+00	164	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 25.04.2026 12:30 ✓	1	[{"added": {}}]	7	1
193	2026-04-16 15:17:40.201808+00	165	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 25.04.2026 13:00 ✓	1	[{"added": {}}]	7	1
194	2026-04-16 15:21:12.076792+00	2	Ворожейкина Ирина Вячеславовна (5-11 классы)	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0431\\u0438\\u043d\\u0435\\u0442"]}}]	10	1
195	2026-04-16 15:22:10.502083+00	2	Ворожейкина Ирина Вячеславовна (5-11 классы)	2	[{"changed": {"fields": ["\\u0422\\u0435\\u043b\\u0435\\u0444\\u043e\\u043d"]}}]	10	1
196	2026-04-16 15:22:28.174098+00	1	Ганиева Маргарита Викторовна (1-4 классы, дошкольники)	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0431\\u0438\\u043d\\u0435\\u0442"]}}]	10	1
197	2026-04-16 15:24:04.378059+00	2	Ворожейкина Ирина Вячеславовна (5-11 классы)	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0431\\u0438\\u043d\\u0435\\u0442"]}}]	10	1
198	2026-04-16 15:27:34.400932+00	1	Консультация психолога	3		9	1
199	2026-04-16 15:40:58.732691+00	11	пири → Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
200	2026-04-17 05:26:24.505263+00	1	Ганиева Маргарита Викторовна (1-4 классы, дошкольники)	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0431\\u0438\\u043d\\u0435\\u0442"]}}]	10	1
201	2026-04-17 05:27:00.669204+00	1	Ганиева Маргарита Викторовна (1-4 классы, дошкольники)	2	[{"changed": {"fields": ["\\u041a\\u0430\\u0431\\u0438\\u043d\\u0435\\u0442"]}}]	10	1
202	2026-04-17 05:28:18.903836+00	12	Червякава Ульяна Ильинична → Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
203	2026-04-17 05:28:27.634263+00	153	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 21.04.2026 08:15 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
204	2026-04-17 05:28:27.640087+00	155	Ганиева Маргарита Викторовна (1-4 классы, дошкольники) | 21.04.2026 09:30 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
205	2026-04-17 11:14:21.058975+00	1	Ганиева Маргарита Викторовна (1-6 классы, дошкольники)	2	[{"changed": {"fields": ["\\u041a\\u043b\\u0430\\u0441\\u0441\\u044b/\\u043a\\u0430\\u0442\\u0435\\u0433\\u043e\\u0440\\u0438\\u044f"]}}]	10	1
206	2026-04-17 11:14:31.018972+00	2	Ворожейкина Ирина Вячеславовна (7-11 классы)	2	[{"changed": {"fields": ["\\u041a\\u043b\\u0430\\u0441\\u0441\\u044b/\\u043a\\u0430\\u0442\\u0435\\u0433\\u043e\\u0440\\u0438\\u044f"]}}]	10	1
207	2026-04-17 19:44:12.026406+00	17	/ → Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
208	2026-04-17 19:44:12.036608+00	16	test → Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
209	2026-04-17 19:46:55.663214+00	18	/ → Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
210	2026-04-17 20:17:30.128945+00	154	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 21.04.2026 09:00 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
211	2026-04-17 20:17:30.132384+00	164	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 25.04.2026 12:30 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
212	2026-04-17 20:17:30.137676+00	165	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 25.04.2026 13:00 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
213	2026-04-17 20:33:58.190616+00	2	Ворожейкина Ирина Вячеславовна (7-11 классы)	2	[{"changed": {"fields": ["\\u041f\\u0443\\u0442\\u044c \\u043a \\u0444\\u043e\\u0442\\u043e \\u0432 \\u0444\\u0430\\u0439\\u043b\\u0430\\u0445 \\u0441\\u0430\\u0439\\u0442\\u0430"]}}]	10	1
214	2026-04-17 20:34:06.742875+00	1	Ганиева Маргарита Викторовна (1-6 классы, дошкольники)	2	[{"changed": {"fields": ["\\u041f\\u0443\\u0442\\u044c \\u043a \\u0444\\u043e\\u0442\\u043e \\u0432 \\u0444\\u0430\\u0439\\u043b\\u0430\\u0445 \\u0441\\u0430\\u0439\\u0442\\u0430"]}}]	10	1
215	2026-04-17 20:44:50.570178+00	165	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 25.04.2026 13:00 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
216	2026-04-17 20:45:02.764111+00	19	/ → Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
217	2026-04-17 20:49:58.762959+00	1	Ганиева Маргарита Викторовна (1-6 классы, дошкольники)	2	[{"changed": {"fields": ["Email \\u0434\\u043b\\u044f \\u0443\\u0432\\u0435\\u0434\\u043e\\u043c\\u043b\\u0435\\u043d\\u0438\\u0439"]}}]	10	1
218	2026-04-17 20:50:51.099109+00	20	 → Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | None	3		8	1
219	2026-04-17 20:50:56.376754+00	160	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 25.04.2026 10:00 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
220	2026-04-24 05:36:45.744682+00	166	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 28.04.2026 08:15 ✓	1	[{"added": {}}]	7	1
221	2026-04-24 05:37:01.464628+00	167	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 28.04.2026 09:00 ✓	1	[{"added": {}}]	7	1
222	2026-04-24 05:37:17.682597+00	168	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 28.04.2026 09:30 ✓	1	[{"added": {}}]	7	1
223	2026-04-24 05:37:41.139806+00	169	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 28.04.2026 10:00 ✓	1	[{"added": {}}]	7	1
224	2026-04-24 05:38:00.131549+00	170	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 30.04.2026 08:15 ✓	1	[{"added": {}}]	7	1
225	2026-04-24 05:38:26.72569+00	171	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 30.04.2026 09:00 ✓	1	[{"added": {}}]	7	1
226	2026-04-24 05:38:42.398351+00	172	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 30.04.2026 09:30 ✓	1	[{"added": {}}]	7	1
227	2026-04-24 05:38:55.236047+00	173	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 30.04.2026 10:00 ✓	1	[{"added": {}}]	7	1
228	2026-05-04 08:34:12.502247+00	174	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 05.05.2026 08:15 ✓	1	[{"added": {}}]	7	1
229	2026-05-04 08:34:27.706152+00	175	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 05.05.2026 09:00 ✓	1	[{"added": {}}]	7	1
230	2026-05-04 08:34:48.20627+00	176	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 05.05.2026 09:30 ✓	1	[{"added": {}}]	7	1
231	2026-05-04 08:35:05.214443+00	177	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 05.05.2026 10:00 ✓	1	[{"added": {}}]	7	1
232	2026-05-04 08:35:29.897752+00	178	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 07.05.2026 08:15 ✓	1	[{"added": {}}]	7	1
233	2026-05-04 08:35:48.203297+00	179	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 07.05.2026 09:00 ✓	1	[{"added": {}}]	7	1
234	2026-05-04 08:36:47.597763+00	180	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 07.05.2026 10:00 ✓	1	[{"added": {}}]	7	1
235	2026-05-04 08:37:09.544132+00	181	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 08.05.2026 14:00 ✓	1	[{"added": {}}]	7	1
236	2026-05-04 08:37:30.216904+00	182	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 08.05.2026 14:30 ✓	1	[{"added": {}}]	7	1
237	2026-05-04 08:37:46.99759+00	183	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 08.05.2026 15:00 ✓	1	[{"added": {}}]	7	1
238	2026-05-08 09:28:51.685533+00	184	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 14.05.2026 15:00 ✓	1	[{"added": {}}]	7	1
239	2026-05-08 09:29:08.52058+00	185	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 14.05.2026 15:30 ✓	1	[{"added": {}}]	7	1
240	2026-05-08 09:29:23.699899+00	186	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 14.05.2026 16:00 ✓	1	[{"added": {}}]	7	1
241	2026-05-08 09:29:37.738664+00	187	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 14.05.2026 16:30 ✓	1	[{"added": {}}]	7	1
242	2026-05-18 05:27:40.000452+00	188	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 19.05.2026 08:15 ✓	1	[{"added": {}}]	7	1
243	2026-05-18 05:27:55.733499+00	189	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 19.05.2026 09:00 ✓	1	[{"added": {}}]	7	1
244	2026-05-18 05:28:10.051988+00	190	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 19.05.2026 09:30 ✓	1	[{"added": {}}]	7	1
245	2026-05-18 05:28:21.543385+00	191	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 19.05.2026 10:00 ✓	1	[{"added": {}}]	7	1
246	2026-05-18 05:28:39.13779+00	192	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 21.05.2026 14:30 ✓	1	[{"added": {}}]	7	1
247	2026-05-18 05:28:52.951547+00	193	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 21.05.2026 15:00 ✓	1	[{"added": {}}]	7	1
248	2026-05-18 05:29:06.838053+00	194	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 21.05.2026 15:30 ✓	1	[{"added": {}}]	7	1
249	2026-05-18 05:29:20.135635+00	195	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 21.05.2026 16:00 ✓	1	[{"added": {}}]	7	1
250	2026-05-18 08:41:19.314835+00	192	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 21.05.2026 14:30 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
251	2026-05-18 08:41:19.345256+00	194	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 21.05.2026 15:30 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
252	2026-05-18 08:42:07.506379+00	190	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 19.05.2026 09:30 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
253	2026-05-18 08:43:38.483314+00	188	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 19.05.2026 08:15 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
254	2026-05-18 10:24:49.165741+00	57	Отставных Каролина Александровна → Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
255	2026-05-18 10:25:33.210955+00	55	Анпилогов Леонид Иванович → Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
256	2026-05-18 10:26:14.375573+00	56	Анпилогов Леонид Иванович → Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
257	2026-05-18 10:54:45.950876+00	74	пьто → Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
258	2026-05-18 10:55:30.305198+00	188	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 19.05.2026 08:15 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
259	2026-05-18 10:59:32.655876+00	84	ewew → Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
260	2026-05-18 10:59:43.307706+00	188	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 19.05.2026 08:15 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
261	2026-05-18 11:17:39.861912+00	54	 → Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | None	3		8	1
262	2026-05-18 11:19:46.245993+00	196	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 21.05.2026 00:00 ✓	1	[{"added": {}}]	7	1
263	2026-05-18 11:20:16.291418+00	196	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 22.05.2026 00:00 ✓	2	[{"changed": {"fields": ["\\u0414\\u0430\\u0442\\u0430"]}}]	7	1
264	2026-05-18 11:27:36.851154+00	93	dhfrhre → Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
265	2026-05-18 11:27:48.143794+00	196	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 22.05.2026 00:00 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
266	2026-05-18 11:27:57.746135+00	92	56е → Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
267	2026-05-18 11:28:11.595209+00	190	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 19.05.2026 09:30 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
268	2026-05-18 11:28:27.144312+00	196	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 22.05.2026 00:00 ✓	3		7	1
269	2026-05-18 12:43:21.897487+00	59	Левченко Павел александрович → Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
270	2026-05-18 12:44:00.887873+00	195	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 21.05.2026 16:00 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
271	2026-05-18 13:54:44.257533+00	197	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 01.11.2026 15:54 ✓	1	[{"added": {}}]	7	1
272	2026-05-18 13:58:21.627326+00	1	Ганиева Маргарита Викторовна (1-6 классы, дошкольники)	2	[{"changed": {"fields": ["Email \\u0434\\u043b\\u044f \\u0443\\u0432\\u0435\\u0434\\u043e\\u043c\\u043b\\u0435\\u043d\\u0438\\u0439"]}}]	10	1
273	2026-05-18 13:58:33.56689+00	97	32w45234 → Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
274	2026-05-18 13:58:43.270078+00	197	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 01.11.2026 15:54 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
275	2026-05-18 13:59:24.349789+00	197	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 01.11.2026 15:54 ✗	3		7	1
276	2026-05-22 19:11:29.641967+00	198	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 25.05.2026 10:00 ✓	1	[{"added": {}}]	7	1
277	2026-05-22 19:11:49.988163+00	199	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 25.05.2026 10:30 ✓	1	[{"added": {}}]	7	1
278	2026-05-22 19:12:14.99952+00	200	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 25.05.2026 11:00 ✓	1	[{"added": {}}]	7	1
279	2026-05-22 19:12:38.74346+00	201	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 26.05.2026 10:00 ✓	1	[{"added": {}}]	7	1
280	2026-05-22 19:12:58.541843+00	202	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 26.05.2026 10:30 ✓	1	[{"added": {}}]	7	1
281	2026-05-22 19:13:14.64262+00	203	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 26.05.2026 11:00 ✓	1	[{"added": {}}]	7	1
282	2026-05-22 19:13:33.052993+00	204	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 29.05.2026 10:00 ✓	1	[{"added": {}}]	7	1
283	2026-05-22 19:14:14.842629+00	205	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 29.05.2026 10:30 ✓	1	[{"added": {}}]	7	1
284	2026-05-22 19:14:32.311137+00	206	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 29.05.2026 11:00 ✓	1	[{"added": {}}]	7	1
285	2026-05-22 19:15:01.654174+00	207	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 29.05.2026 11:30 ✓	1	[{"added": {}}]	7	1
286	2026-05-22 19:16:55.153881+00	99	Ttt → Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
287	2026-05-22 19:17:39.357251+00	198	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 25.05.2026 10:00 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
288	2026-05-25 05:50:39.545316+00	101	Мамедов Тагир Станиславович → Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | Психологическое собеседование дошкольников	3		8	1
289	2026-05-25 05:51:14.966828+00	198	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 25.05.2026 10:00 ✓	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
290	2026-05-26 07:55:56.562343+00	205	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 29.05.2026 10:30 ✗	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
291	2026-05-26 07:55:56.566184+00	206	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 29.05.2026 11:00 ✗	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
292	2026-05-26 07:55:56.569463+00	207	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 29.05.2026 11:30 ✗	2	[{"changed": {"fields": ["\\u0414\\u043e\\u0441\\u0442\\u0443\\u043f\\u0435\\u043d"]}}]	7	1
293	2026-05-29 08:59:21.142752+00	208	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 08.06.2026 13:00 ✓	1	[{"added": {}}]	7	1
294	2026-05-29 08:59:36.665341+00	209	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 08.06.2026 13:30 ✓	1	[{"added": {}}]	7	1
295	2026-05-29 08:59:57.514525+00	210	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 08.06.2026 14:00 ✓	1	[{"added": {}}]	7	1
296	2026-05-29 09:42:20.736181+00	211	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 08.06.2026 14:30 ✓	1	[{"added": {}}]	7	1
297	2026-05-29 09:42:39.382719+00	212	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 10.06.2026 08:30 ✓	1	[{"added": {}}]	7	1
298	2026-05-29 09:42:52.303866+00	213	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 10.06.2026 09:00 ✓	1	[{"added": {}}]	7	1
299	2026-05-29 09:43:05.142725+00	214	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 10.06.2026 09:30 ✓	1	[{"added": {}}]	7	1
300	2026-05-29 09:43:19.235491+00	215	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 11.06.2026 08:30 ✓	1	[{"added": {}}]	7	1
301	2026-05-29 09:43:31.94354+00	216	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 11.06.2026 09:00 ✓	1	[{"added": {}}]	7	1
302	2026-05-29 09:43:43.341684+00	217	Ганиева Маргарита Викторовна (1-6 классы, дошкольники) | 11.06.2026 09:30 ✓	1	[{"added": {}}]	7	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	booking	timeslot
8	booking	appointment
9	booking	appointmenttype
10	booking	psychologist
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-11 07:48:12.150186+00
2	auth	0001_initial	2026-04-11 07:48:12.442646+00
3	admin	0001_initial	2026-04-11 07:48:12.480943+00
4	admin	0002_logentry_remove_auto_add	2026-04-11 07:48:12.488006+00
5	admin	0003_logentry_add_action_flag_choices	2026-04-11 07:48:12.498019+00
6	contenttypes	0002_remove_content_type_name	2026-04-11 07:48:12.540636+00
7	auth	0002_alter_permission_name_max_length	2026-04-11 07:48:12.553395+00
8	auth	0003_alter_user_email_max_length	2026-04-11 07:48:12.56721+00
9	auth	0004_alter_user_username_opts	2026-04-11 07:48:12.57654+00
10	auth	0005_alter_user_last_login_null	2026-04-11 07:48:12.589963+00
11	auth	0006_require_contenttypes_0002	2026-04-11 07:48:12.596184+00
12	auth	0007_alter_validators_add_error_messages	2026-04-11 07:48:12.606995+00
13	auth	0008_alter_user_username_max_length	2026-04-11 07:48:12.632274+00
14	auth	0009_alter_user_last_name_max_length	2026-04-11 07:48:12.653419+00
15	auth	0010_alter_group_name_max_length	2026-04-11 07:48:12.674168+00
16	auth	0011_update_proxy_permissions	2026-04-11 07:48:12.684026+00
17	auth	0012_alter_user_first_name_max_length	2026-04-11 07:48:12.699719+00
18	booking	0001_initial	2026-04-11 07:48:12.746535+00
19	sessions	0001_initial	2026-04-11 07:48:12.772857+00
20	booking	0002_appointmenttype_psychologist_appointment_address_and_more	2026-04-11 08:15:20.039614+00
21	booking	0003_appointment_parent_phone_and_more	2026-04-11 12:45:34.419213+00
22	booking	0004_psychologist_photo	2026-04-11 13:26:15.059672+00
23	booking	0005_alter_psychologist_photo	2026-04-12 12:03:24.139124+00
24	booking	0006_psychologist_email	2026-04-17 19:19:27.102634+00
25	booking	0007_alter_psychologist_photo	2026-06-07 23:49:21.855868+00
26	booking	0008_migrate_photo_paths	2026-06-07 23:49:21.86755+00
27	booking	0009_alter_appointment_appointment_type_and_more	2026-06-07 23:49:21.955395+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
39zx1s6jxctg1jgozn391fkvm7nhf6d3	.eJxVjEEOwiAQRe_C2hBogUGX7nsGMgyMVA0kpV0Z765NutDtf-_9lwi4rSVsPS9hTuIitDj9bhHpkesO0h3rrUlqdV3mKHdFHrTLqaX8vB7u30HBXr61Z6vJOD67kRh8Ggmy4pjAgUHigZQ1zAoVWGd9GqJBPSogNhmcAi3eH_AqN9s:1wCBtO:6CRxt5-44IMxoSGJ0x3wVgVGWuEDvhCBzPupIQ-no5A	2026-04-27 07:39:34.441232+00
xijeopnqdd3sns8ahrvgb66l4f5x0bf6	.eJxVjEEOwiAQRe_C2hCGQgGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTgLEKffLWF-cNsB3bHdZpnnti5TkrsiD9rldSZ-Xg7376Bir9_aFesyB9LGIWgGUAEZjNUh-0GTKmFUZdTkgahA0cEpJheMxzSwS1a8P9XcN7A:1wEDYc:ILoPs0resUYIH0dakIs6g14nnj0dz1U0wV7qSY2ddlA	2026-05-02 21:50:30.167123+00
da1tntji35khfvifu7ibifpvhjzt0zmk	.eJxVjEEOwiAQRe_C2hCGQgGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTgLEKffLWF-cNsB3bHdZpnnti5TkrsiD9rldSZ-Xg7376Bir9_aFesyB9LGIWgGUAEZjNUh-0GTKmFUZdTkgahA0cEpJheMxzSwS1a8P9XcN7A:1wEp9p:NWKiRj5msHRjIbKViB3En7eXTdnrzC86ca3VeZPbXTc	2026-05-04 13:59:25.564477+00
mb62ndvd6lq0slrmantv8j2ilnxkb5wp	.eJxVjEEOwiAQRe_C2hCGQgGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTgLEKffLWF-cNsB3bHdZpnnti5TkrsiD9rldSZ-Xg7376Bir9_aFesyB9LGIWgGUAEZjNUh-0GTKmFUZdTkgahA0cEpJheMxzSwS1a8P9XcN7A:1wEp9r:lmhDSdseQ7XKsuc8PHIVD_hURwHt7_8xjURtNhu3AjE	2026-05-04 13:59:27.575746+00
wajibkyoxsh1gcgnryzri052dn0x9yug	.eJxVjEEOwiAQRe_C2hCGQgGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTgLEKffLWF-cNsB3bHdZpnnti5TkrsiD9rldSZ-Xg7376Bir9_aFesyB9LGIWgGUAEZjNUh-0GTKmFUZdTkgahA0cEpJheMxzSwS1a8P9XcN7A:1wEp9t:2Tiq0RviyQfYmueVjOiz6aiJBsQGN7kCIF4OVVh5JNQ	2026-05-04 13:59:29.77262+00
gadq04inp0rzzr4z8p1sgcoztn7z31t6	.eJxVjEEOwiAQRe_C2hCGQgGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTgLEKffLWF-cNsB3bHdZpnnti5TkrsiD9rldSZ-Xg7376Bir9_aFesyB9LGIWgGUAEZjNUh-0GTKmFUZdTkgahA0cEpJheMxzSwS1a8P9XcN7A:1wEpGp:V_4P4dPhZLvHUYCmLAjzjR_3pA8J5nXew9BBVHcLBMs	2026-05-04 14:06:39.373032+00
wcybbunrfsw1fecjh3m4byo69ab803ce	.eJxVjEEOwiAQRe_C2hCGQgGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTgLEKffLWF-cNsB3bHdZpnnti5TkrsiD9rldSZ-Xg7376Bir9_aFesyB9LGIWgGUAEZjNUh-0GTKmFUZdTkgahA0cEpJheMxzSwS1a8P9XcN7A:1wEqQD:Bg6hq-6c9igl9FBWd2fUhbUX1swdCKi6zHQQw-RwV2c	2026-05-04 15:20:25.872105+00
iei5ikld043iecd4c263l63f8xx4ugd6	.eJxVjEEOwiAQRe_C2hCGQgGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTgLEKffLWF-cNsB3bHdZpnnti5TkrsiD9rldSZ-Xg7376Bir9_aFesyB9LGIWgGUAEZjNUh-0GTKmFUZdTkgahA0cEpJheMxzSwS1a8P9XcN7A:1wG9Bd:wc4QOyq4bKE_-ibKJ0KUgxn0yDYAOa4i1JSKUDZD9ZE	2026-05-08 05:34:45.758132+00
e6eho3mxiqnicqu5w98n6mju6du5asjj	.eJxVjEEOwiAQRe_C2hCGQgGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTgLEKffLWF-cNsB3bHdZpnnti5TkrsiD9rldSZ-Xg7376Bir9_aFesyB9LGIWgGUAEZjNUh-0GTKmFUZdTkgahA0cEpJheMxzSwS1a8P9XcN7A:1wHFho:qNXnrg8C93fX0zi2AQVZU26EoIFGtu8lHaxXSPFew2s	2026-05-11 06:44:32.365541+00
2v3nv2qpv3nig2a9pj6jkbqdzxnh48c1	.eJxVjEEOwiAQRe_C2hCGQgGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTgLEKffLWF-cNsB3bHdZpnnti5TkrsiD9rldSZ-Xg7376Bir9_aFesyB9LGIWgGUAEZjNUh-0GTKmFUZdTkgahA0cEpJheMxzSwS1a8P9XcN7A:1wLHUT:lo6YdjjW71zoWOpvSoWiuOVGPc6hn4C9w_iBXDU56Rk	2026-05-22 09:27:25.772778+00
xydzv4alod4sd2h10xeqjhlza96aexk3	.eJxVjEEOwiAQRe_C2hCGQgGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTgLEKffLWF-cNsB3bHdZpnnti5TkrsiD9rldSZ-Xg7376Bir9_aFesyB9LGIWgGUAEZjNUh-0GTKmFUZdTkgahA0cEpJheMxzSwS1a8P9XcN7A:1wLzw3:9MS5CPbEcqy1E_UjQ5bAwC2NmSeAw7aLQWh5oO9PMGU	2026-05-24 08:54:51.553989+00
cfl3o9asy52pinem1xpoihh8d9hd62hw	.eJxVjEEOwiAQRe_C2hCGQgGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTgLEKffLWF-cNsB3bHdZpnnti5TkrsiD9rldSZ-Xg7376Bir9_aFesyB9LGIWgGUAEZjNUh-0GTKmFUZdTkgahA0cEpJheMxzSwS1a8P9XcN7A:1wMh6m:FBfeswRyUMjgGr1D0W_VG_TAxcq2tNlCw8GUlGjO4GM	2026-05-26 07:00:48.240413+00
h1536rjcpij5na700r80xzdrts0urr73	.eJxVjEEOwiAQRe_C2hCGQgGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTgLEKffLWF-cNsB3bHdZpnnti5TkrsiD9rldSZ-Xg7376Bir9_aFesyB9LGIWgGUAEZjNUh-0GTKmFUZdTkgahA0cEpJheMxzSwS1a8P9XcN7A:1wMh6o:T80w3MvdoOGPAdW6ybjmUZO45kLAYRzgyuApNuHgaCc	2026-05-26 07:00:50.43493+00
mrdejipod1kff6kn2kisfofwy8j42r5l	.eJxVjEEOwiAQRe_C2hCGQgGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTgLEKffLWF-cNsB3bHdZpnnti5TkrsiD9rldSZ-Xg7376Bir9_aFesyB9LGIWgGUAEZjNUh-0GTKmFUZdTkgahA0cEpJheMxzSwS1a8P9XcN7A:1wQVE7:vA8GPo5N-QZBV7WiRMtun2fvC46luhCGZ9Pi9s6L5IE	2026-06-05 19:08:07.855822+00
m2xmd11n7kf5tg9it9szwk4w6ff2h101	.eJxVjEEOwiAQRe_C2hCGQgGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTgLEKffLWF-cNsB3bHdZpnnti5TkrsiD9rldSZ-Xg7376Bir9_aFesyB9LGIWgGUAEZjNUh-0GTKmFUZdTkgahA0cEpJheMxzSwS1a8P9XcN7A:1wQVGq:P8eD908vmXii8U5iBjQFvw0cvFWZck4RAWerAgMr2BY	2026-06-05 19:10:56.168871+00
spxum9lsc0de9m2rv1kvtkovrs4i3dct	.eJxVjEEOwiAQRe_C2hCGQgGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTgLEKffLWF-cNsB3bHdZpnnti5TkrsiD9rldSZ-Xg7376Bir9_aFesyB9LGIWgGUAEZjNUh-0GTKmFUZdTkgahA0cEpJheMxzSwS1a8P9XcN7A:1wRO9k:WphCQUZ_qpxWhkGAL_oNAQJU4dAbM-Zte_-BS8Z4uxw	2026-06-08 05:47:16.558146+00
zgqtqqhulxeuzt3514tjhn2fl6myu5yk	.eJxVjEEOwiAQRe_C2hCGQgGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTgLEKffLWF-cNsB3bHdZpnnti5TkrsiD9rldSZ-Xg7376Bir9_aFesyB9LGIWgGUAEZjNUh-0GTKmFUZdTkgahA0cEpJheMxzSwS1a8P9XcN7A:1wRmeB:0iHdbsBR_1UvaHfFQZ2AANUW2EGbogLZz8rp3pbZUKo	2026-06-09 07:56:19.565598+00
fsspp0hkdbdup1ddo1ajdimqci3o6iki	.eJxVjEEOwiAQRe_C2hCGQgGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTgLEKffLWF-cNsB3bHdZpnnti5TkrsiD9rldSZ-Xg7376Bir9_aFesyB9LGIWgGUAEZjNUh-0GTKmFUZdTkgahA0cEpJheMxzSwS1a8P9XcN7A:1wRmeD:RbDNaBBOAbQUqoPZgEi3K0A69gCclz6Z1_qFxvICB2I	2026-06-09 07:56:21.64841+00
74p2iovoaoydpiwl6vr7yiwgxne3713f	.eJxVjEEOwiAQRe_C2hCGQgGX7j0DGZhBqoYmpV0Z765NutDtf-_9l4i4rTVunZc4kTgLEKffLWF-cNsB3bHdZpnnti5TkrsiD9rldSZ-Xg7376Bir9_aFesyB9LGIWgGUAEZjNUh-0GTKmFUZdTkgahA0cEpJheMxzSwS1a8P9XcN7A:1wWNaL:44bpLx9dN45ua2G5A_JoEooANdRvefNxVzpkYGOLthw	2026-06-22 00:11:21.928501+00
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 40, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: booking_appointment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.booking_appointment_id_seq', 115, true);


--
-- Name: booking_appointmenttype_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.booking_appointmenttype_id_seq', 2, true);


--
-- Name: booking_appointmenttype_psychologists_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.booking_appointmenttype_psychologists_id_seq', 3, true);


--
-- Name: booking_psychologist_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.booking_psychologist_id_seq', 2, true);


--
-- Name: booking_timeslot_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.booking_timeslot_id_seq', 217, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 302, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 10, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 27, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: booking_appointment booking_appointment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_appointment
    ADD CONSTRAINT booking_appointment_pkey PRIMARY KEY (id);


--
-- Name: booking_appointment booking_appointment_slot_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_appointment
    ADD CONSTRAINT booking_appointment_slot_id_key UNIQUE (slot_id);


--
-- Name: booking_appointmenttype_psychologists booking_appointmenttype__appointmenttype_id_psych_0feed29c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_appointmenttype_psychologists
    ADD CONSTRAINT booking_appointmenttype__appointmenttype_id_psych_0feed29c_uniq UNIQUE (appointmenttype_id, psychologist_id);


--
-- Name: booking_appointmenttype booking_appointmenttype_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_appointmenttype
    ADD CONSTRAINT booking_appointmenttype_pkey PRIMARY KEY (id);


--
-- Name: booking_appointmenttype_psychologists booking_appointmenttype_psychologists_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_appointmenttype_psychologists
    ADD CONSTRAINT booking_appointmenttype_psychologists_pkey PRIMARY KEY (id);


--
-- Name: booking_psychologist booking_psychologist_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_psychologist
    ADD CONSTRAINT booking_psychologist_pkey PRIMARY KEY (id);


--
-- Name: booking_timeslot booking_timeslot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_timeslot
    ADD CONSTRAINT booking_timeslot_pkey PRIMARY KEY (id);


--
-- Name: booking_timeslot booking_timeslot_psychologist_id_date_time_9b85cb28_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_timeslot
    ADD CONSTRAINT booking_timeslot_psychologist_id_date_time_9b85cb28_uniq UNIQUE (psychologist_id, date, "time");


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: booking_appointment_appointment_type_id_1864480b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX booking_appointment_appointment_type_id_1864480b ON public.booking_appointment USING btree (appointment_type_id);


--
-- Name: booking_appointmenttype_ps_appointmenttype_id_2e1d39c1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX booking_appointmenttype_ps_appointmenttype_id_2e1d39c1 ON public.booking_appointmenttype_psychologists USING btree (appointmenttype_id);


--
-- Name: booking_appointmenttype_psychologists_psychologist_id_682759cc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX booking_appointmenttype_psychologists_psychologist_id_682759cc ON public.booking_appointmenttype_psychologists USING btree (psychologist_id);


--
-- Name: booking_timeslot_psychologist_id_a40890a0; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX booking_timeslot_psychologist_id_a40890a0 ON public.booking_timeslot USING btree (psychologist_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: booking_appointment booking_appointment_appointment_type_id_1864480b_fk_booking_a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_appointment
    ADD CONSTRAINT booking_appointment_appointment_type_id_1864480b_fk_booking_a FOREIGN KEY (appointment_type_id) REFERENCES public.booking_appointmenttype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: booking_appointment booking_appointment_slot_id_72b9094f_fk_booking_timeslot_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_appointment
    ADD CONSTRAINT booking_appointment_slot_id_72b9094f_fk_booking_timeslot_id FOREIGN KEY (slot_id) REFERENCES public.booking_timeslot(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: booking_appointmenttype_psychologists booking_appointmentt_appointmenttype_id_2e1d39c1_fk_booking_a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_appointmenttype_psychologists
    ADD CONSTRAINT booking_appointmentt_appointmenttype_id_2e1d39c1_fk_booking_a FOREIGN KEY (appointmenttype_id) REFERENCES public.booking_appointmenttype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: booking_appointmenttype_psychologists booking_appointmentt_psychologist_id_682759cc_fk_booking_p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_appointmenttype_psychologists
    ADD CONSTRAINT booking_appointmentt_psychologist_id_682759cc_fk_booking_p FOREIGN KEY (psychologist_id) REFERENCES public.booking_psychologist(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: booking_timeslot booking_timeslot_psychologist_id_a40890a0_fk_booking_p; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.booking_timeslot
    ADD CONSTRAINT booking_timeslot_psychologist_id_a40890a0_fk_booking_p FOREIGN KEY (psychologist_id) REFERENCES public.booking_psychologist(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict qCdmFOG7ktw3TSoQAVst72tJgRL7USxFnklcKk01mGokav6fRjfKSf5hgJh6hjg

