services:
  - type: web
    name: lyceum23-psychologist
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn lyceum23.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      # SENTRY_DSN задаётся вручную в дашборде Render → Environment