# Generated by Django 5.0.6 on 2026-04-11 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('form_type', models.CharField(choices=[('consultation', 'Обычная консультация'), ('preschool_exam', 'Обследование дошкольника')], help_text='Определяет какие поля показываются при записи', max_length=20, verbose_name='Тип формы')),
                ('description', models.TextField(blank=True, verbose_name='Описание для пользователя')),
            ],
            options={
                'verbose_name': 'Тип приёма',
                'verbose_name_plural': 'Типы приёмов',
            },
        ),
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('grades', models.CharField(max_length=100, verbose_name='Классы/категория')),
                ('cabinet', models.CharField(blank=True, max_length=50, verbose_name='Кабинет')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Психолог',
                'verbose_name_plural': 'Психологи',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Место проживания'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='child_birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения ребёнка'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='child_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО ребёнка'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='kindergarten',
            field=models.CharField(blank=True, max_length=200, verbose_name='Номер детского сада'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='parent_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО родителя'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='grade',
            field=models.CharField(blank=True, max_length=10, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='booking.timeslot', verbose_name='Слот'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='who',
            field=models.CharField(blank=True, choices=[('student', 'Ученик'), ('parent', 'Родитель'), ('preschooler', 'Родитель дошкольника'), ('teacher', 'Учитель')], max_length=20, verbose_name='Кто записывается'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.appointmenttype', verbose_name='Тип приёма'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='psychologist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='booking.psychologist', verbose_name='Психолог'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('psychologist', 'date', 'time')},
        ),
    ]
