# Generated by Django 5.0.6 on 2026-04-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointmenttype_psychologist_appointment_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон родителя'),
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='psychologists',
            field=models.ManyToManyField(blank=True, related_name='appointment_types', to='booking.psychologist', verbose_name='Доступно у психологов'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='who',
            field=models.CharField(blank=True, choices=[('student', 'Ученик'), ('parent', 'Родитель'), ('teacher', 'Учитель')], max_length=20, verbose_name='Кто записывается'),
        ),
        migrations.AlterField(
            model_name='appointmenttype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='appointmenttype',
            name='form_type',
            field=models.CharField(choices=[('consultation', 'Обычная консультация'), ('preschool_exam', 'Обследование дошкольника')], max_length=20, verbose_name='Тип формы'),
        ),
    ]
