# Generated by Django 5.0.6 on 2026-04-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_appointment_parent_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='photo',
            field=models.ImageField(blank=True, upload_to='psychologists/', verbose_name='Фото'),
        ),
    ]
