# Generated by Django 5.0.6 on 2026-04-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_psychologist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='photo',
            field=models.CharField(blank=True, help_text='Например: images/psychologists/photo1.jpg', max_length=200, verbose_name='Путь к фото в файлах сайта'),
        ),
    ]
