# Generated by Django 5.0.6 on 2026-04-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_psychologist_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email для уведомлений'),
        ),
    ]
