# Generated by Django 5.2.13 on 2026-06-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_psychologist_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='photo',
            field=models.ImageField(blank=True, upload_to='psychologists/', verbose_name='Фото'),
        ),
    ]
