# Generated by Django 5.2.13 on 2026-06-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_psychologist_photo'),
    ]

    operations = [
    ]
