# Generated by Django 5.2.13 on 2026-06-07 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_migrate_photo_paths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.appointmenttype', verbose_name='Тип приёма'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='booking.psychologist', verbose_name='Психолог'),
        ),
    ]
