# Generated by Django 5.2.13 on 2026-06-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_appointment_appointment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='photo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фото (путь к файлу)'),
        ),
    ]
