# Generated by Django 5.2.15 on 2026-06-08 16:53

import django.db.models.deletion
from django.db import migrations, models


def normalize_existing_phones(apps, schema_editor):
    """Привести все существующие номера к единому формату."""
    Appointment = apps.get_model('booking', 'Appointment')

    from booking.phone_utils import normalize_phone

    for a in Appointment.objects.iterator():
        changed = False

        if a.phone:
            normalized = normalize_phone(a.phone)
            if normalized and normalized != a.phone:
                a.phone = normalized
                changed = True

        if a.parent_phone:
            normalized = normalize_phone(a.parent_phone)
            if normalized and normalized != a.parent_phone:
                a.parent_phone = normalized
                changed = True

        if changed:
            a.save(update_fields=['phone', 'parent_phone'])


def reverse_func(apps, schema_editor):
    """Откат — ничего не делаем, данные остаются нормализованными."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_change_photo_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(blank=True, help_text='Причина обращения, жалобы, пожелания', verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(help_text='Психолог, дата и время (заполняется автоматически при записи через сайт)', on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='booking.timeslot', verbose_name='Время приёма'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы закрыть это время для записи', verbose_name='Доступен'),
        ),
        migrations.RunPython(normalize_existing_phones, reverse_func),
    ]
